### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Mohitkumar33**
Hello guys,
Here is my home page of the E-commerce website project. Please review my code and correct if I am wrong or something can be improved at any point.
visit my home page deployed on the link below

https://fastcomshop.netlify.app/

### CODE REVIEW

**Review by AmishMishra11 — COMMENTED** [review]
The code is good but we have to use some styling from our component library so please add that.
also, work on responsiveness

**Comment by Mohitkumar33** [comment]
> The code is good but we have to use some styling from our component library so please add that. also, work on responsiveness

Thanks for reviewing Amish. Yes I will work on responsiveness and regarding the usage of components from the component library, I used cards and badge icons from my component library.
Thanks Amish

**Review by Bharatrathod-81 — COMMENTED** [review]
looks good

**Comment by Mohitkumar33** [comment]
> looks good

Thanks, bharatrathod

**Pull request merged**
